# Generated by Django 4.2.16 on 2025-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
